"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MultiClientMac.py']
DATA_FILES = ['ClientData.ini','60x60.png']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'lvyanlogo.ico'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
